version: '3.3'
services:

 mobilidade-backend:
    image: node:16
    container_name: mobilidade-backend
    restart: always
    working_dir: /app
    command: bash -c 'npm install && npm run prod && node dist/server.js'
    volumes:
      - ./:/app
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

    environment:
      - NODE_ENV=production
      - PORT=3300
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=5PfKm0POuZ5h
      - ELASTIC_HOST=https://vps35731.publiccloud.com.br:9200
    ports:
      - "3000:3300"

